package classes;

public class Dialogues {
    public static final String[][] DEATH_MESSAGES = {
            {"<Player> has cout"},
            {"<Killer> set <Player> as a null pointer"},
            {"<Player> had an encounter with Ma'am Cherry"},
            {"<Player> fell into the backrooms"},
            {"<Player> got hashmapped by <Killer>"},
            {"<Player> got popped from the stack by <Killer>"},
            {"<Player> dequeued by <Killer>"},
            {"PlayerList.remove(<Player>)"},
            {"<Player> took an L"},
            {"<Player> got rip bozo'd by <Killer>"},
            {"<Killer> put <Player> in a recursive function"},
            {"<Killer> threw <Player>Exception"},
            {"<Player> tried throwing an error"},
            {"<Player> got stackoverflowed"},
            {"<Player> got caught playing games by JoeMaria"},
            {"<Player> got womanji'd"},
            {"<Killer>: @Meta AI please kick <Player> from the gc"},
            {"<Player>'s game thread was put in a deadlock"},
            {"<Killer> set @<Player>'s health to 0"},
            {"<Player>'s game thread was put in a deadlock"},
            {"<Player>Thread.wait()"},
            {"DELETE FROM tblPlayer WHERE name = \"<Player>\";"},
            {"<Player> forgot to bring their footmops"},
            {"<Player> was asked by Sir Ugang to program in Assembly"},
            {"<Player> did not survive 5 nights at Freddy's"},
            {"<Player> forgot to set the UIController in the fxml file"},
            {"throw logic_error(<Player> + \" should be dead\")"},
            {"if(name == \"<Player>\") {setPlayerHealth(0)}"},
            {"<Player> got hit by joemama"},
            {"<Player> was not the Imposter"},
            {"<Player> got kamehameha'd"},
            {"<Player> died of natural causes"},
            {"<Player> got a visit from Jose Rizal"},
            {"<Killer> asked <Player> to manually show Radix Sort with [1, 30, 659483530683]"},
            {"<Player> got SWATted by <Killer>"},
            {"<Player> did a JFK Cosplay"},
            {"<Player> got sent to the gulag"},
            {"<Player> did a movie marathon of the Emoji Movie, Morbius, and Snow White"},
            {"<Player> got set to the Nether"},
            {"<Player> lost their rights"},
            {"<Player> got arrested by the ICC"},
            {"<Killer>: @mods, plz ban @<Player> <33333 xoxoxo"},
            {"<Player>, put these foolish ambitions to rest"},
            {"<Player> was not cool and normal"},
            {"si <Player> ay namatay"},
            {"Kono bun wa jissai ni wa nanra juyona imi o motte orazu, mata kakusareta himitsu mo arimasen. <Player> hon'yaku ni jikan o saite itadaki, moshiwakegozaimasen."},
            {"<Player> got BSOD"},
            {"<Player> got banned by the admins for not being a discord kitten"},
            {"<Player> got admitted to an asylum"},
            {"<Player> got cancelled on twitter"},
            {"<Player> got banned for profanity"},
            {"<Player> got hit by a blue shell "},
            {"<Player> caught some strays"},
            {"<Player> did not prepare their cheatsheet for DAA"},
            {"<Player> got replaced by AI"},
            {"Jarvis, ban <Player>"},
            {"<Player>'s ID was confiscated for wearing PE uniform"},
            {"<Player> tried logging in to tsg.noc"},
            {"<Player> was selected for squid game"},
            {"<Player> tried to swim in lava"},
            {"<Player> touched grass"},
            {"<Player> got Thanos snapped"},
            {"Owemji <Player>-chan! You just died OwO Hope you get better soon-nyan!"},
            {"<Player> skill-issue"},
            {"<Player> could not find the One Piece"},
            {"<Player>, Pro Tip: Don't get hit"},
            {"<Player> got hit by an ad wall"},
            {"<Player> was invited to the Talk Tuah Podcast"},
            {"<Player> died due to ligma"},
            {"<Player> clicked a link to get free Robux"},
            {"<Player>'s commit cannot be merged successfully"},
            {"<Player> was using WILDConnect Wifi to play"},
            {"<Player> tried downloading free RAM"},
            {"<Player> tried playing Albion Online (a free sandbox mmorpg in which you get to write your own story)"},
            {"<Player> got hooked on League of Legends"},
            {"Santa put <Player> on the naughty list"},
            {"<Killer> forced <Player> to watch all 77 episodes of Skibidi Toilet"},
            {"<Player> wanted to be <Killer>'s sigma rizzler"},
            {"<Killer> wanted <Player> to be their little pogchamp"},
            {"<Player> tried to speedrun getting killed on bbc.io"},
            {"<Killer> set <Player> variable as transient"},
            {"GradeChum made an error computing <Player>'s health"},
            {"<Player> said LAIR was better than BLAIR"},
            {"<Player>: \"It's the ping!\""},
            {"<Player> forgot to put #include<iostream>"},
            {"<Player> got stuck in the loading screen"},
            {"<Killer> saw <Player>'s browser history"},
            {"Gipa Tulfo ni <Killer> si <Player>"},
            {"<Killer> called <Player> about their car's extended warranty"},
            {"<Killer> called an ambulance for <Player>"},
            {"<Killer> spawned a creeper behind <Player>"},
            {"<Player> used string instead of String"},
            {"System.out.println(<Player> + \" has died\")"},
            {"<Killer> rick rolled <Player>"},
            {"Ga laag pa si <Player> sa Seaside"},
            {"<Player>'s index cannot be found"},
            {"<Player> did not follow proper naming conventions"},
            {"<Player>: \"He's right behind me isn't he\""},
            {"<Killer: *Teleports behind <Player>: \"Nothing personal kid\""},
            {"<Player>NotFoundException"},
            {"<Player>'s brainrot was too strong"},
            {"<Player> forgot to add mysql-connector to their library"},
            {"Thank you <Player> for reminding us to increase player health"},
            {"<Killer> showed <Player> that the bullets are working correctly"},
            {"<Player> could not pull the 5*"},
            {"<Player> did not win the 50/50 pity"},
            {"<Killer> told <Player> to get out of their swamp"},
            {"<Killer> killed <Player> at electrical"},
            {"<Player> failed to MLG water bucket their fall"},
            {"<Player> tried using WITS"},
    };
}
